# The plugin source is a fixed-output derivation generated by xcaddy, whose
# `go.mod` records the go version it was built with. The shared package set follows a
# different channel per platform, so a single `hash` only holds for one of them:
# built for linux alone, where the servers that need it run.
{
  lib,
  caddy,
}:
(caddy.withPlugins {
  plugins = [
    # https://github.com/caddy-dns/cloudflare/tags
    "github.com/caddy-dns/cloudflare@v0.2.4"
  ];
  hash = "sha256-xRJ5evsAJ2akg47j3Bt6YDXJOgX88B/rKNP50KSVyNY=";
}).overrideAttrs
  (prevAttrs: {
    meta = prevAttrs.meta // {
      platforms = lib.platforms.linux;
    };
  })
