{
  lib,
  python3Packages,
  fetchFromGitHub,
  versionCheckHook,
  nix-update-script,
}:
let
  # dependencies missing from nixpkgs, added to the python scope so that they share the interpreter
  # and package set with the application itself
  vendoredNames = map (lib.removeSuffix ".nix") (lib.attrNames (builtins.readDir ./python-modules));
  pythonPackages = python3Packages.overrideScope (
    final: _:
    lib.genAttrs vendoredNames (name: final.callPackage (./python-modules + "/${name}.nix") { })
  );
in
pythonPackages.buildPythonApplication (finalAttrs: {
  pname = "scanoss-py";
  version = "1.54.2";
  pyproject = true;

  src = fetchFromGitHub {
    owner = "scanoss";
    repo = "scanoss.py";
    tag = "v${finalAttrs.version}";
    hash = "sha256-WRSc6MKIDnAlKE4J7NVVPyD9sVvHFbZCrnQPdeEQ994=";
  };

  # twine is only needed for publishing to PyPI, and the build date is generated by the upstream
  # release process, an empty file makes the cli fall back to the current date instead of warning
  postPatch = ''
    substituteInPlace pyproject.toml \
      --replace-fail '["setuptools", "wheel", "twine"]' '["setuptools", "wheel"]'
    touch src/scanoss/data/build_date.txt
  '';

  build-system = with pythonPackages; [ setuptools ];

  dependencies =
    with pythonPackages;
    [
      binaryornot
      crc
      crc32c
      cyclonedx-python-lib
      google-api-core
      grpcio
      importlib-resources
      jsonschema
      packageurl-python
      pathspec
      progress
      protobuf
      protoc-gen-openapiv2
      pyopenssl
      pypac
      requests
      scanoss-winnowing # fast_winnowing extra
    ]
    ++ cyclonedx-python-lib.optional-dependencies.validation;

  pythonImportsCheck = [ "scanoss.cli" ];

  passthru = {
    updateScript = nix-update-script { };
    # picked up by the overlay and exposed as `scanoss-py-<name>`
    vendored = lib.getAttrs vendoredNames pythonPackages;
  };

  nativeInstallCheckInputs = [ versionCheckHook ];
  versionCheckProgramArg = "--version";
  doInstallCheck = true;

  strictDeps = true;
  __structuredAttrs = true;

  meta = {
    description = "Simple Python library to leverage the SCANOSS APIs";
    homepage = "https://github.com/scanoss/scanoss.py";
    changelog = "https://github.com/scanoss/scanoss.py/blob/${finalAttrs.src.tag}/CHANGELOG.md";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ mirkolenz ];
    mainProgram = "scanoss-py";
  };
})
