name: update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: generate-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2
      - name: capture base commit
        id: base
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - uses: DeterminateSystems/determinate-nix-action@4eea0b33e3d1f02ecfe37cf16e7204c424009606 # v3
        with:
          extra-conf: |
            accept-flake-config = true
            log-lines = 200
            commit-lock-file-summary = chore(deps/nix): update
      - run: nix run . -- update-all --commit
        env:
          GH_TOKEN: ${{ github.token }}
      - name: remove unstaged changes
        run: git restore .
      - name: build pr body
        run: git log --reverse --format='## %s%n%n%b' ${{ steps.base.outputs.sha }}..HEAD > "$RUNNER_TEMP/pr-body.md"
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        id: pr
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-deps
          delete-branch: true
          title: "chore(deps): update"
          body-path: ${{ runner.temp }}/pr-body.md
      - name: automerge
        run: gh pr merge --auto --rebase ${{ steps.pr.outputs.pull-request-number }}
        if: steps.pr.outputs.pull-request-number != ''
        env:
          GH_TOKEN: ${{ github.token }}
